replicaCount: 1

image:
  repository: proyectodevopsem/shipping-service
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

probes:
  path: /shipping/c
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 60
  livenessProbe:
    initialDelaySeconds: 15
    periodSeconds: 60

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
