replicaCount: 1

image:
  repository: proyectodevopsem/orders-service
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
